configR:
	cmake -B build .\
		-DFAISS_ENABLE_GPU=ON \
		-DFAISS_ENABLE_PYTHON=ON \
		-DBUILD_TESTING=ON \
		-DBUILD_SHARED_LIBS=ON \
		-DFAISS_ENABLE_C_API=ON \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
		-DCMAKE_CUDA_ARCHITECTURES="80;80"
configD:
	cmake -B build .\
		-DFAISS_ENABLE_GPU=ON \
		-DFAISS_ENABLE_PYTHON=ON \
		-DBUILD_TESTING=ON \
		-DBUILD_SHARED_LIBS=ON \
		-DFAISS_ENABLE_C_API=ON \
		-DCMAKE_BUILD_TYPE=Debug \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
		-DCMAKE_CUDA_ARCHITECTURES="80;80"